import React from 'react';
import About from "@/viewer/About";
import {Metadata} from "next";

export const metadata: Metadata = {
    title: 'about',
    description: 'Generated by create next app',
}
const Page = () => {
    return <About/>
};

export default Page;