import React from 'react';
import About from "@/components/viewer/About";
import {Metadata} from "next";
import Link from "next/link";

export const metadata: Metadata = {
    title: 'contacts',
    description: 'Generated by create next app',
}
const Page = () => {
    return (
        <div>
            contacts
        </div>
    )
};

export default Page;