import React from 'react';
import {Metadata} from "next";
import style from "../../../public/styles/posts.module.css";
import Link from "next/link";
import {dictionary} from "@/public/dictionary/dictionary";

export const metadata: Metadata = {
    title: 'create post',
    description: 'Generated by create next app',
}
const Page = () => {
    const {newPostTitle , back, link} = dictionary.en.posts
    return (
        <div className={style.create}>
            <span className={style.title}>{newPostTitle}</span>
            <Link href={link} className={style.link}>{back}</Link>

        </div>
    );
};

export default Page;